# Generated by Django 5.1.1 on 2024-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conpany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('logo', models.ImageField(upload_to='', verbose_name='company logo')),
                ('email', models.EmailField(max_length=254, verbose_name='company email')),
                ('phone', models.BigIntegerField(verbose_name='company phone phone number write in the discription eg +123 09135762867')),
                ('is_edit', models.BooleanField(default=False, verbose_name='do not click to edit company')),
                ('w_link', models.URLField(verbose_name=' company whatsapp link')),
                ('F_link', models.URLField(verbose_name=' company facebook link')),
                ('t_link', models.URLField(verbose_name=' company twitter link')),
                ('in_link', models.URLField(verbose_name=' company instargram link')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=500, verbose_name='product name')),
                ('price', models.IntegerField(default=0, verbose_name='products pricing')),
                ('shot_des', models.CharField(max_length=200, verbose_name='short title discription')),
                ('prod_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='product id to get the particular product')),
                ('features1', models.CharField(blank=True, max_length=100, null=True, verbose_name='features3 in a strait line short features')),
                ('is_ver', models.BooleanField(default=False, verbose_name='do not click to verify products')),
            ],
        ),
    ]
