# Generated by Django 5.1.1 on 2024-12-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypilotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='features2 in a strait line short features'),
        ),
        migrations.AddField(
            model_name='product',
            name='features3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='features3 in a strait line short features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='features1 in a strait line short features'),
        ),
    ]
